import { defineProject } from "./schema";

export const splitly = defineProject({
  slug: "splitly",
  title: { es: "Splitly", en: "Splitly" },
  shortDescription: {
    es: "Aplicación móvil y PWA para registrar gastos compartidos, calcular balances y sugerir la manera más simple de saldar cuentas.",
    en: "Mobile app and PWA for recording shared expenses, calculating balances, and suggesting the simplest way to settle them.",
  },
  summary: {
    es: "Splitly transforma gastos grupales en balances claros y pagos sugeridos mediante una experiencia mobile-first diseñada para reducir cálculos manuales y confusión entre participantes.",
    en: "Splitly turns group expenses into clear balances and suggested settlements through a mobile-first experience designed to reduce manual calculations and confusion between participants.",
  },
  category: "application",
  commercialType: "mvp",
  commercialLabel: { es: "MVP demostrativo", en: "Demonstration MVP" },
  status: "published",
  year: 2026,
  featured: true,
  featuredOrder: 4,
  coverImage: {
    src: "/projects/splitly/cover.webp",
    width: 1672,
    height: 941,
    aspectRatio: "16/9",
    alt: {
      es: "Vista amplia de Splitly con grupos, gastos y el resumen de balances en dispositivos móviles.",
      en: "Wide Splitly view featuring groups, expenses, and balance summaries on mobile devices.",
    },
  },
  thumbnailImage: {
    src: "/projects/splitly/thumbnail.webp",
    width: 1407,
    height: 1055,
    aspectRatio: "4/3",
    alt: {
      es: "Aplicación Splitly mostrando gastos compartidos, balances y pagos sugeridos.",
      en: "Splitly application showing shared expenses, balances, and suggested settlements.",
    },
  },
  liveUrl: "https://splitlybyfuentivo.vercel.app/",
  services: [
    { es: "Diseño de producto mobile-first", en: "Mobile-first product design" },
    { es: "Desarrollo de aplicación web progresiva", en: "Progressive web application development" },
    { es: "Diseño de lógica de balances", en: "Balance logic design" },
  ],
  technologies: [
    "Next.js",
    "React",
    "TypeScript",
    "Tailwind CSS",
    "shadcn/ui",
    "Motion",
    "Lucide React",
    "PWA Manifest",
    "localStorage",
    "SVG",
    "Web Share API",
    "Clipboard API",
    "Vercel",
  ],
  tags: ["PWA", "Shared expenses", "Mobile-first", "Bilingual"],
  challenge: {
    es: "En salidas, viajes y compras grupales, diferentes personas pagan distintos gastos y no todos participan por igual, provocando confusión sobre quién debe dinero y cuánto corresponde pagar.",
    en: "During outings, trips, and group purchases, different people cover different expenses and participation varies, creating confusion about who owes money and how much each person should pay.",
  },
  objective: {
    es: "Reducir cálculos manuales, prevenir errores y convertir gastos grupales en balances y pagos fáciles de comprender.",
    en: "Reduce manual calculations, prevent errors, and turn group expenses into balances and payments that are easy to understand.",
  },
  solution: {
    es: "Una aplicación mobile-first que permite crear grupos, registrar gastos, elegir participantes y métodos de división, calcular balances y generar pagos sugeridos entre miembros.",
    en: "A mobile-first application for creating groups, recording expenses, selecting participants and splitting methods, calculating balances, and generating suggested payments between members.",
  },
  features: [
    { es: "Landing de presentación y onboarding de tres pasos.", en: "Product landing page and three-step onboarding." },
    { es: "Instalación como PWA.", en: "PWA installation." },
    { es: "Creación y edición de grupos.", en: "Group creation and editing." },
    { es: "Miembros con avatares por iniciales.", en: "Members with initial-based avatars." },
    { es: "Registro de gastos y selección de quién pagó.", en: "Expense recording and payer selection." },
    { es: "Selección de participantes.", en: "Participant selection." },
    { es: "División igual entre todos o entre algunos participantes.", en: "Equal splitting across all or selected participants." },
    { es: "División por porcentaje o cantidades exactas.", en: "Percentage-based or exact-amount splitting." },
    { es: "Validaciones monetarias y cálculos en centavos.", en: "Monetary validation and cent-based calculations." },
    { es: "Historial de gastos y balances individuales.", en: "Expense history and individual balances." },
    { es: "Totales pagados y consumidos.", en: "Paid and consumed totals." },
    { es: "Algoritmo de pagos sugeridos.", en: "Suggested-payment algorithm." },
    { es: "Marcar pagos como realizados y deshacer liquidaciones cuando aplica.", en: "Mark settlements as paid and undo them when applicable." },
    { es: "Gráfico radial por miembro y actividad reciente.", en: "Radial chart by member and recent activity." },
    { es: "Copiar, compartir mediante Web Share API y enviar por WhatsApp.", en: "Copy, share through the Web Share API, and send through WhatsApp." },
    { es: "Grupos precargados y persistencia local.", en: "Preloaded groups and local persistence." },
    { es: "Español e inglés, responsive, accesible y con microinteracciones.", en: "Spanish and English, responsive, accessible, and enhanced with microinteractions." },
  ],
  seo: {
    es: {
      title: "Splitly — Aplicación PWA para dividir gastos compartidos",
      description: "MVP demostrativo mobile-first para registrar gastos grupales, calcular balances y proponer pagos simples entre participantes.",
      image: "/projects/splitly/cover.webp",
    },
    en: {
      title: "Splitly — PWA for Splitting Shared Expenses",
      description: "Mobile-first demonstration MVP for recording group expenses, calculating balances, and suggesting simple settlements between participants.",
      image: "/projects/splitly/cover.webp",
    },
  },
});
